# Generated by Django 5.1 on 2024-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_doctors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(default='media/doctor_images/doctor.jpg', upload_to='doctor_images/'),
        ),
    ]
